/* This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 */
#pragma once

enum TweenAlgorithm
{
    LINEAR,
    EASE_IN_QUADRATIC,
    EASE_OUT_QUADRATIC,
    EASE_INOUT_QUADRATIC,
    EASE_IN_CUBIC,
    EASE_OUT_CUBIC,
    EASE_INOUT_CUBIC,
    EASE_IN_QUARTIC,
    EASE_OUT_QUARTIC,
    EASE_INOUT_QUARTIC,
    EASE_IN_QUINTIC,
    EASE_OUT_QUINTIC,
    EASE_INOUT_QUINTIC,
    EASE_IN_SINE,
    EASE_OUT_SINE,
    EASE_INOUT_SINE,
    EASE_IN_EXPONENTIAL,
    EASE_OUT_EXPONENTIAL,
    EASE_INOUT_EXPONENTIAL,
    EASE_IN_CIRCULAR,
    EASE_OUT_CIRCULAR,
    EASE_INOUT_CIRCULAR,
};

enum TweenProperty
{
    TWEEN_PROPERTY_HEIGHT,
    TWEEN_PROPERTY_WIDTH,
    TWEEN_PROPERTY_ANGLE,
    TWEEN_PROPERTY_ALPHA,
    TWEEN_PROPERTY_X,
    TWEEN_PROPERTY_Y,
    TWEEN_PROPERTY_X_ORIGIN,
    TWEEN_PROPERTY_Y_ORIGIN,
    TWEEN_PROPERTY_X_OFFSET,
    TWEEN_PROPERTY_Y_OFFSET,
    TWEEN_PROPERTY_FONT_SIZE
};
